export const movies = [
    {
        title: 'The Blind Side',
        date: 'November 20, 2009',
        casts: ['Sandra Bullock', 'Tim McGraw', 'Quinton Aaron', 'Kathy Bates'],
        poster: 'https://i.pinimg.com/originals/3c/88/2c/3c882cec494361f55144ea3114f04bb8.jpg',
        trailer: 'https://www.youtube.com/watch?v=gvqj_Tk_kuM',
        summary: "Michael Oher (Quinton Aaron), a homeless black teen, has drifted in and out of the school system for years. Then Leigh Anne Tuohy (Sandra Bullock) and her husband, Sean (Tim McGraw), take him in. The Tuohys eventually become Michael's legal guardians, transforming both his life and theirs. Michael's tremendous size and protective instincts make him a formidable force on the gridiron, and with help from his new family and devoted tutor, he realizes his potential as a student and football player.",
        year: '2009',
        genre: ['Sports', 'Drama'],
        category: 'sports',
        progress: 0,
        duration: '2m 29s',
        started: false,
        ended: false,
        hovered: false
    },
    {
        title: 'Kung Fu Dunk',
        date: 'February 7, 2008',
        casts: ['Jay Chou', 'Eric Tsang', 'Charlene Choi', 'Bolin Chen'],
        poster: 'https://alchetron.com/cdn/Kung-Fu-Dunk-images-f80732e4-ad0f-482d-b29b-34ec020e1c5.jpg',
        trailer: 'https://www.youtube.com/watch?v=PxNqkdHhLVI',
        summary: "Shi-Jie (Jay Chou) was abandoned by his parents as a child and left with the master of the local kung fu school. As he grows up, he vigorously trains in martial arts and develops an ability to predict his opponents' moves before they occur. This ability serves him well on the basketball court and he catches the eye of Chen-Li, a shady businessman who convinces Shi-Jie to join a local college's basketball team to help them defeat a rival school who is so brutal they have been banned in the U.S.",
        year: '2008',
        genre: ['Action', 'Comedy', 'Sports'],
        category: 'sports',
        progress: 0,
        duration: '1m 53s',
        started: false,
        ended: false,
        hovered: false
    },
    {
        title: 'Space Jam',
        date: 'November 10, 1996',
        casts: ['Michael Jordan', 'Billy West', 'Wayne Knight', 'Theresa Randle', 'Danny DeVito'],
        poster: 'https://summerofthearts.org/wp-content/uploads/Space-Jam.jpg',
        trailer: 'https://www.youtube.com/watch?v=oKNy-MWjkcU',
        summary: "Swackhammer (Danny DeVito), an evil alien theme park owner, needs a new attraction at Moron Mountain. When his gang, the Nerdlucks, heads to Earth to kidnap Bugs Bunny (Billy West) and the Looney Tunes, Bugs challenges them to a basketball game to determine their fate. The aliens agree, but they steal the powers of NBA basketball players, including Larry Bird (Larry Bird) and Charles Barkley (Charles Barkley) -- so Bugs gets some help from superstar Michael Jordan (Michael Jordan).",
        year: '1996',
        genre: ['Comedy', 'Children\'s film', 'Adventure', 'Science fiction', 'Sports', 'Fantasy', 'Animation'],
        category: 'sports',
        progress: 0,
        duration: '1m 7s',
        started: false,
        ended: false,
        hovered: false
    },
    {
        title: 'Warrior',
        date: 'September 9, 2011',
        casts: ['Joel Edgerton', 'Tom Hardy', 'Jennifer Morrison', 'Frank Grillo', 'Nick Nolte'],
        poster: 'https://www.joblo.com/wp-content/uploads/2011/03/warrior-poster1-1.jpg',
        trailer: 'https://www.youtube.com/watch?v=I5kzcwcQA1Q',
        summary: "An estranged family finds redemption in the unlikeliest of places: the MMA ring. Tommy (Tom Hardy), an ex-Marine with a tragic past, returns home and enlists his father (Nick Nolte), a recovering alcoholic and former wrestling coach, to train him for \"Sparta,\" the biggest MMA tournament ever held. But when Tommy's underdog brother, Brendan (Joel Edgerton), fights his way into the tournament, the two brothers must finally confront each other and the forces that pulled them apart.",
        year: '2011',
        genre: ['Action', 'Martial arts', 'Sports', 'Drama'],
        category: 'sports',
        progress: 0,
        duration: '2m 32s',
        started: false,
        ended: false,
        hovered: false
    },
    {
        title: 'The Way Back',
        date: 'March 6, 2020',
        casts: ['Ben Affleck', 'Al Madrigal', 'Michaela Watkins', 'Janina Gavankar'],
        poster: 'https://m.media-amazon.com/images/M/MV5BYjBjMTgyYzktN2U0Mi00YTJhLThkZDQtZmM1ZDlmNWMwZDQ3XkEyXkFqcGdeQXVyMDU5MDEyMA@@._V1_.jpg',
        trailer: 'https://www.youtube.com/watch?v=VzNJVSsjE-I',
        summary: "Jack Cunningham was a high school basketball superstar who suddenly walked away from the game for unknown reasons. Years later, he's now stuck in a meaningless job and struggling with alcoholism - the very thing that ruined his marriage and his hope for a better life. But Jack soon gets a shot at redemption when he becomes the basketball coach for his alma mater, a programme that has fallen on hard times since his teenage glory days.",
        year: '2020',
        genre: ['Sports', 'Drama'],
        category: 'sports',
        progress: 0,
        duration: '2m 13s',
        started: false,
        ended: false,
        hovered: false
    },
    {
        title: 'Amateur',
        date: 'April 6, 2018',
        casts: ['Michael Rainey Jr.'],
        poster: 'https://www.themoviedb.org/t/p/original/nWUvlNxKSMdegAoY5eMOqPwMKIb.jpg',
        trailer: 'https://www.youtube.com/watch?v=0cQ3sBXpNtw',
        summary: "A gifted basketball player struggles to fit in with his new team at an elite prep school where he is confronted by corruption and greed.",
        year: '2018',
        genre: ['Drama', 'Sports'],
        category: 'sports',
        progress: 0,
        duration: '2m 21s',
        started: false,
        ended: false,
        hovered: false
    },
    {
        title: 'Thunderstruck',
        date: 'August 24, 2012',
        casts: ['Kevin Durant', 'Taylor Gray', 'Brandon T. Jackson', 'Doc Shaw', 'Jim Belushi'],
        poster: 'https://media-cache.cinematerial.com/p/500x/tr9udpl9/thunderstruck-dvd-movie-cover.jpg?v=1456573108',
        trailer: 'https://www.youtube.com/watch?v=65qyPfZe9Eg',
        summary: "A teenage klutz (Taylor Gray) becomes the star of his high-school basketball team when he magically acquires the abilities of his hero, NBA star Kevin Durant -- but the switch leaves Durant unable to score.",
        year: '2012',
        genre: ['Sports', 'Comedy'],
        category: 'sports',
        progress: 0,
        duration: '2m 31s',
        started: false,
        ended: false,
        hovered: false
    },
    {
        title: 'A Prayer Before Dawn',
        date: 'May 19, 2017',
        casts: ['Joe Cole'],
        poster: 'https://www.themoviedb.org/t/p/original/hjkRZjxyBItViHg53i3upKmPM0A.jpg',
        trailer: 'https://www.youtube.com/watch?v=Mp88Nuci68c',
        summary: "The amazing true story of Billy Moore, an English boxer incarcerated in Thailand's most notorious prison. Thrown into a world of drugs and violence, he finds his best chance to escape is to fight his way out in Muay Thai tournaments.",
        year: '2017',
        genre: ['Action', 'Drama', 'Sports', 'Crime film'],
        category: 'sports',
        progress: 0,
        duration: '2m 25s',
        started: false,
        ended: false,
        hovered: false
    },
    {
        title: 'Shaolin Soccer',
        date: 'July 12, 2001',
        casts: ['Stephen Chow', 'Zhao Wei', 'Ng Man-tat', 'Patrick Tse', 'Danny Chan Kwok-kwan'],
        poster: 'https://img.goldposter.com/2016/01/Shaolin-Soccer_poster_goldposter_com_7.bmp',
        trailer: 'https://www.youtube.com/watch?v=t0C9BC8PLbE',
        summary: "All his life, an ordinary young man (Stephen Chow) has been treated like dirt. Still, he's never given up believing that all the world's problems could be solved with a little kung fu. So he's teaming up with a band of misfits - six friends who were kung fu masters in their youth - to form a soccer team that only he believes has a chance to win a $1 million grand prize. Together, they're going to apply their hidden talents to a whole new game -- and soccer will never be the same.",
        year: '2001',
        genre: ['Action', 'Comedy', 'Martial arts', 'Fantasy', 'Sports'],
        category: 'sports',
        progress: 0,
        duration: '1m 55s',
        started: false,
        ended: false,
        hovered: false
    },
    {
        title: 'Rudy',
        date: 'September 18, 1993',
        casts: ['Sean Astin', 'Ned Beatty', 'Charles S. Dutton', 'Lili Taylor', 'Robert Prosky'],
        poster: 'https://images.pristineauction.com/61/615499/main_1487694726-Rudy-Ruettiger-Signed-Rudy-27-x-40-Movie-Poster-Photo-Inscribed-Never-Quit-JSA-Hologram-PristineAuction.com.jpg',
        trailer: 'https://www.youtube.com/watch?v=firK4y-3bKw',
        summary: "Rudy Ruettiger (Sean Astin) wants to play football at the University of Notre Dame, but has neither the money for tuition nor the grades to qualify for a scholarship. Rudy redoubles his efforts to get out of the steel mill where his father works when his best friend (Christopher Reed) dies in an accident there. Overcoming his dyslexia thanks to his friend and tutor, D-Bob (Jon Favreau), Rudy gains admission to Notre Dame and begins to fight his way onto the school's fabled football team.",
        year: '1993',
        genre: ['Sports', 'Drama', 'Children\'s film'],
        category: 'sports',
        progress: 0,
        duration: '2m 8s',
        started: false,
        ended: false,
        hovered: false
    }
]